export const TEXTES = {
  titrePokedex: "Pokédex",
  chargementListe: "Loading Pokémon...",
  chargementDetail: "Loading...",
  erreurPrefixe: "Error: ",
  pokemonIntrouvable: "Pokémon not found",
  retourListe: "Back to list",
  about: "About",
  poids: "Weight",
  taille: "Height",
  talents: "Abilities",
  statistiquesBase: "Base Stats",
  rechercher: "Search",
  trierPar: "Sort by:",
  triNumero: "Number",
  triNom: "Name",
  boutonTri: "Sort the list",
  numero: "number",
  type: "Type",
  illustrationDe: "Artwork of",
  uniteKg: "kg",
  uniteM: "m",
  pokemonPrecedent: "Previous Pokémon",
  pokemonSuivant: "Next Pokémon",
  sur: "out of",
  theme: "Theme:",
  themeClair: "Light",
  themeSombre: "Dark",
  boutonOptions: "Display options",
  fermerOptions: "Close options",
};
