export const TEXTES = {
  titrePokedex: "Pokédex",
  chargementListe: "Chargement des Pokémon...",
  chargementDetail: "Chargement...",
  erreurPrefixe: "Erreur : ",
  pokemonIntrouvable: "Pokémon introuvable",
  retourListe: "Retour à la liste",
  about: "À propos",
  poids: "Poids",
  taille: "Taille",
  talents: "Talents",
  statistiquesBase: "Statistiques de base",
  rechercher: "Rechercher",
  trierPar: "Trier par :",
  triNumero: "Numéro",
  triNom: "Nom",
  boutonTri: "Trier la liste",
  numero: "numéro",
  type: "Type",
  illustrationDe: "Illustration de",
  uniteKg: "kg",
  uniteM: "m",
  pokemonPrecedent: "Pokémon précédent",
  pokemonSuivant: "Pokémon suivant",
};
